### ISSUE TITLE
can't read Modbus Meter

### ISSUE THREAD

**Issue by Chris591** [volkszaehler/mbmd#201]
Hi,

Ich komme von EVCC und wollte mehr daten aus meinem Meter auslesen und speichern und da wurde mir MBMD empfohlen.
Leider bekomme ich hier aber diesen Output mit den gleichen Settings von Docker und auch der USB Dongle ist gleich konfiguriert.
EVCC kann ich den Meter ordentlich auslesen.

mit einem Scan findet er nichts.

hab es auch mit einem anderen USB Adapter probiert - wieder das gleiche EVCC läuft - MBMD die gleichen Probleme.

Gruß,
Chris

> 2021/04/27 08:51:41 mbmd 0.13 (fa6b574),
> 2021/04/27 08:51:41 config: using /etc/mbmd.yaml,
> 2021/04/27 08:51:41 config: creating RTU connection for /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 (9600baud, 8N1),
> 2021/04/27 08:51:41 config: declared device SDM:1.0,
> 2021/04/27 08:51:41 httpd: starting api at 0.0.0.0:8080,
> 2021/04/27 08:51:41 mqtt: connecting mbmd at [tcp://10.201.1.10:1883],
> 2021/04/27 08:51:43 initialized device SDM1.1: {SDM SDM Eastron SDM630    0},
> 2021/04/27 08:51:43 device SDM1.1 did not respond (1/3): read failed: permission denied,
> 2021/04/27 08:51:44 device SDM1.1 did not respond (2/3): read failed: permission denied,
> 2021/04/27 08:51:45 device SDM1.1 did not respond (3/3): read failed: permission denied,
> 2021/04/27 08:51:46 device SDM1.1 is offline,
> 2021/04/27 08:51:48 device SDM1.1 is offline - reactivating,
> 2021/04/27 08:51:48 device SDM1.1 did not respond (1/3): read failed: permission denied,
> 2021/04/27 08:51:49 device SDM1.1 did not respond (2/3): read failed: permission denied,
> 2021/04/27 08:51:50 device SDM1.1 did not respond (3/3): read failed: permission denied,
> 2021/04/27 08:51:51 device SDM1.1 is offline,
> 2021/04/27 08:51:53 device SDM1.1 is offline - reactivating,
> ....

**Comment by andig** [comment]
Also im logfile steht permission denied. Ich würde sagen das ist das Problem.

**Comment by Chris591** [comment]
Ja aber wieso und wo kann ich schauen?
EVCC läuft auf dem gleichem Raspberry PI mit dem gleichen settings vom Docker ohne Probleme.
Ist es das er nicht auf den ModBus zugreifen kann oder das er nicht auf den Meter auf alle werte zugreifen kann?
Was macht MBMD anders?

MBMD config:
```
# adapters are referenced by device
adapters:
- device: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  baudrate: 9600
  comset: 8N1 # "8E1" needs be quoted as string or will error

# list of devices
devices:
- name: grid
  type: sdm
  id: 1
  adapter: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

```

> /usr/share/mbmd $ docker run --rm -v $(pwd)/mbmd.yaml:/etc/mbmd.yaml -v /dev:/dev -p 8080:8080 --device /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 volkszaehler/mbmd:latest run --config /etc/mbmd.yaml
> 2021/04/27 12:39:15 mbmd 0.13 (fa6b574)
> 2021/04/27 12:39:15 config: using /etc/mbmd.yaml
> 2021/04/27 12:39:15 config: creating RTU connection for /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 (9600baud, 8N1)
> 2021/04/27 12:39:15 config: declared device SDM:1.0
> 2021/04/27 12:39:15 httpd: starting api at 0.0.0.0:8080
> 2021/04/27 12:39:15 mqtt: connecting mbmd at [tcp://10.201.1.10:1883]
> 2021/04/27 12:39:17 initialized device SDM1.1: {SDM SDM Eastron SDM630    0}
> 2021/04/27 12:39:17 device SDM1.1 did not respond (1/3): read failed: permission denied
> 2021/04/27 12:39:18 device SDM1.1 did not respond (2/3): read failed: permission denied
> 2021/04/27 12:39:19 device SDM1.1 did not respond (3/3): read failed: permission denied
> 

EVCC config:
```
meters:
- name: grid
  type: modbus
  model: sdm
  device: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  baudrate: 9600
  comset: 8N1
  id: 1
```

> /usr/share/evcc $ docker run --rm -v $(pwd)/evcc.yaml:/etc/evcc.yaml -v /dev:/dev -p 7070:7070 --device /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 --entrypoint evcc andig/evcc:latest meter
> Power: 583W
>
