### ISSUE TITLE
Topic ID in Homie MQTT entspricht nicht der Convention

### ISSUE THREAD

**Issue by chrostek** [volkszaehler/mbmd#33]
Ich habe versucht MBMD mit Homie MQTT in Verbindung mit openHAB 2 zu nutzen. Leider meldet mir openHAB einen Fehler:

ID segment 'mbmd_sdm1.1_meter' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.

Das ist auch korrekt so, laut Homie Convention:
https://homieiot.github.io/specification/#topic-ids
darf da kein Punkt drin sein. Das Problem liegt also bei "sdm1.1".
Meine Config sieht so aus:

```
# mqtt config
mqtt:
  broker: localhost:1883
  topic:
  user: 
  password: 
  clientid: mbmd
  qos: 0
  clean: true
  homie: mbmd

# adapters are referenced by device
adapters:
- device: /dev/ttyUSB0
  baudrate: 9600
  comset: 8N1

# list of devices
devices:
- type: sdm
  id: 1
  adapter: /dev/ttyUSB0
- type: sdm
  id: 2
  adapter: /dev/ttyUSB0
- type: sdm
  id: 3
  adapter: /dev/ttyUSB0
```

Ich habe also aktuell 3 SDM Geräte, die entsprechend durchnumeriert werden.
Im einfachsten Falle müsste für Homie einfach ein "." durch ein "-" ersetzt werden. 

Danke

Viele Grüße
Sebastian
